CREATE DATABASE Minions
use master

CREATE TABLE Users(
 Id BIGINT IDENTITY  NOT NULL,
 Username VARCHAR(30) UNIQUE NOT NULL,
 Password VARCHAR(26) NOT NULL,
 ProfilePicture VARBINARY(MAX),
 LastLoginTime DATETIME,
 IsDeleted BIT 
 CONSTRAINT PK_Users PRIMARY KEY (Id)
)

ALTER TABLE Users
DROP CONSTRAINT PK_Users

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY (Id, Username)

ALTER TABLE Users
ADD CONSTRAINT CHK_ProfilePictureSize CHECK (DATALENGTH(ProfilePicture) <= 900 * 1024)

ALTER TABLE Users
ADD CONSTRAINT CHK_PasswordSize CHECK (DATALENGTH(Password) >= 5)

ALTER TABLE Users
ADD DEFAULT GETDATE() FOR LastLoginTime